/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAlert: typeof import('vuetify/components')['VAlert']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/components')['VAppBarNavIcon']
    VAvatar: typeof import('vuetify/components')['VAvatar']
    VBottomNavigation: typeof import('vuetify/components')['VBottomNavigation']
    VBtn: typeof import('vuetify/components')['VBtn']
    VBtnToggle: typeof import('vuetify/components')['VBtnToggle']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardSubtitle: typeof import('vuetify/components')['VCardSubtitle']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCheckbox: typeof import('vuetify/components')['VCheckbox']
    VCol: typeof import('vuetify/components')['VCol']
    VCombobox: typeof import('vuetify/components')['VCombobox']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VDivider: typeof import('vuetify/components')['VDivider']
    VHover: typeof import('vuetify/components')['VHover']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VListSubheader: typeof import('vuetify/components')['VListSubheader']
    VMain: typeof import('vuetify/components')['VMain']
    VMenu: typeof import('vuetify/components')['VMenu']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/components')['VOverlay']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/components')['VProgressLinear']
    VRadio: typeof import('vuetify/components')['VRadio']
    VRadioGroup: typeof import('vuetify/components')['VRadioGroup']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSheet: typeof import('vuetify/components')['VSheet']
    VSlider: typeof import('vuetify/components')['VSlider']
    VSlideYTransition: typeof import('vuetify/components')['VSlideYTransition']
    VSnackbar: typeof import('vuetify/components')['VSnackbar']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VSwitch: typeof import('vuetify/components')['VSwitch']
    VTab: typeof import('vuetify/components')['VTab']
    VTabs: typeof import('vuetify/components')['VTabs']
    VTextField: typeof import('vuetify/components')['VTextField']
    VToolbar: typeof import('vuetify/components')['VToolbar']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
    VTooltip: typeof import('vuetify/components')['VTooltip']
    VVirtualScroll: typeof import('vuetify/components')['VVirtualScroll']
  }
}
